// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2
// Source: shortUrl.proto

package server

import (
    "context"

    "github.com/shorturl/short-url/zero_remake/shorturl_rpc/internal/logic"
    "github.com/shorturl/short-url/zero_remake/shorturl_rpc/internal/svc"
    "github.com/shorturl/short-url/zero_remake/shorturl_rpc/types/shortUrl"
)

type ShortUrlServer struct {
	svcCtx *svc.ServiceContext
	shortUrl.UnimplementedShortUrlServer
}

func NewShortUrlServer(svcCtx *svc.ServiceContext) *ShortUrlServer {
	return &ShortUrlServer{
		svcCtx: svcCtx,
	}
}

func (s *ShortUrlServer) GenerateShortUrl(ctx context.Context, in *shortUrl.GenerateShortUrlRequest) (*shortUrl.GenerateShortUrlResponse, error) {
	l := logic.NewGenerateShortUrlLogic(ctx, s.svcCtx)
	return l.GenerateShortUrl(in)
}

func (s *ShortUrlServer) HandleShort(ctx context.Context, in *shortUrl.HandleShortRequest) (*shortUrl.HandleShortResponse, error) {
	l := logic.NewHandleShortLogic(ctx, s.svcCtx)
	return l.HandleShort(in)
}

func (s *ShortUrlServer) GenerateIDbMySnowflake(ctx context.Context, in *shortUrl.GenerateShortUrlRequest) (*shortUrl.GenerateShortUrlResponse, error) {
	l := logic.NewGenerateIDbMySnowflakeLogic(ctx, s.svcCtx)
	return l.GenerateIDbMySnowflake(in)
}

func (s *ShortUrlServer) FilterByMyBloomFilter(ctx context.Context, in *shortUrl.GenerateShortUrlRequest) (*shortUrl.GenerateShortUrlResponse, error) {
	l := logic.NewFilterByMyBloomFilterLogic(ctx, s.svcCtx)
	return l.FilterByMyBloomFilter(in)
}

func (s *ShortUrlServer) GenerateWithIPLimter(ctx context.Context, in *shortUrl.GenerateShortUrlRequest) (*shortUrl.GenerateShortUrlResponse, error) {
	l := logic.NewGenerateWithIPLimterLogic(ctx, s.svcCtx)
	return l.GenerateWithIPLimter(in)
}
