// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2

package types

type GenerateRequest struct {
	Url        string `form:"url"`        // 原始URL
	Expiration string `form:"expiration"` // 过期时间，例如 "1h", "30m", "1d"
}

type GenerateResponse struct {
	Code     int    `json:"code"`      // 状态码
	ShortUrl string `json:"short_url"` // 生成的短链接
	Message  string `json:"message"`   // 消息
}

type RedirectRequest struct {
	ShortURL string `path:"shortURL"` // 短链接参数
}

type RedirectResponse struct {
	Code         int    `json:"code"`         // 状态码
	OringinalUrl string `json:"original_url"` // 原始URL
	Message      string `json:"message"`      // 消息
}

type UserLoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type UserLoginResponse struct {
	Code        int    `json:"code"`
	Message     string `json:"message"`
	AccessToken string `json:"access_token"`
	ExpiresIn   int64  `json:"expires_in"`
}

type UserRegisterRequset struct {
	Username        string `json:"username"`
	Password        string `json:"password"`
	ConfirmPassword string `json:"confirm_password"`
}

type UserRegisterResponse struct {
	Code int `json:"code"`
}

type QpsResponse struct {
	Code    int     `json:"code"`
	Message string  `json:"message"`
	QPS     float64 `json:"qps"`
}
