// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2
// Source: user-rpc.proto

package server

import (
	"context"

	"example.com/shorturl/short-url/zero_remake/user-rpc/internal/logic"
	"example.com/shorturl/short-url/zero_remake/user-rpc/internal/svc"
	"example.com/shorturl/short-url/zero_remake/user-rpc/types/User"
)

type UserServiceServer struct {
	svcCtx *svc.ServiceContext
	User.UnimplementedUserServiceServer
}

func NewUserServiceServer(svcCtx *svc.ServiceContext) *UserServiceServer {
	return &UserServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServiceServer) Register(ctx context.Context, in *User.RegisterRequest) (*User.RegisterResponse, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UserServiceServer) Login(ctx context.Context, in *User.LoginRequest) (*User.LoginResponse, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}
