// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2

package handler

import (
    "net/http"

    "github.com/shorturl/short-url/zero_remake/shorturl_api/internal/svc"

    "github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
    server.AddRoutes(
        []rest.Route{
            {
                Method:  http.MethodOptions,
                Path:    "/register",
                Handler: PreflightHandler(),
            },
            {
                Method:  http.MethodOptions,
                Path:    "/login",
                Handler: PreflightHandler(),
            },
            {
                Method:  http.MethodPost,
                Path:    "/login",
                Handler: LoginHandler(serverCtx),
            },
            {
                Method:  http.MethodPost,
                Path:    "/register",
                Handler: RegisterHandler(serverCtx),
            },
        },
        rest.WithPrefix("/users"),
    )

	// 短链跳转不需要 JWT，单独注册不带 Jwt 的组
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/:shortURL",
				Handler: RedirectHandler(serverCtx),
			},
		},
		rest.WithPrefix("/shorturls"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/filterbymybloomfilter",
				Handler: FilterByMyBloomFilterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/generate",
				Handler: GenerateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/generatebymysnowflake",
				Handler: GenerateIDbMySnowflakeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/generatewithiplimiter",
				Handler: GenerateWithIPLimterHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/shorturls"),
	)

	// OPTIONS 预检路由不应经过 JWT，单独注册在不带 Jwt 的组里
	server.AddRoutes(
		[]rest.Route{
			{Method: http.MethodOptions, Path: "/filterbymybloomfilter", Handler: PreflightHandler()},
			{Method: http.MethodOptions, Path: "/generate", Handler: PreflightHandler()},
			{Method: http.MethodOptions, Path: "/generatebymysnowflake", Handler: PreflightHandler()},
			{Method: http.MethodOptions, Path: "/generatewithiplimiter", Handler: PreflightHandler()},
		},
		rest.WithPrefix("/shorturls"),
	)

}
